/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 04.03.2026 07:20:37

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10048;
#else
constexpr int kTensorArenaSize = 9024;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,3920 } };
const TfArray<1, float> quant0_scale = { 1, { 0.0036151960957795382, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 98, 40, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 98, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 49, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 49, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data6[3] = { -844, 584, 357, };
const TfArray<1, int> tensor_dimension6 = { 1, { 3 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0011023114202544093, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[3*400] = { 
  -21, -57, -18, 16, -5, -6, 2, -5, 10, -3, 29, 12, 21, -28, 7, -60, -9, -37, -2, 10, 16, 8, 31, -20, 4, 20, 4, 11, 30, -47, 0, -38, -3, -3, -12, 5, 15, 3, 10, -4, -2, 15, -2, -31, 9, -68, 15, -5, -8, -14, -12, 13, -2, 2, 14, -13, 5, 9, 18, 29, 21, -78, 9, -44, 9, 5, 3, 15, 7, 3, 28, -27, -3, 26, -6, -3, 6, -27, -19, -20, -5, 2, 9, 20, 31, 3, 15, -25, 2, 15, 0, -5, 17, -40, -2, -6, 1, -22, -10, 21, 4, 15, 8, -15, 3, 2, 8, 6, 6, -30, 19, 2, -11, -48, -14, -8, 22, 7, 12, -22, 7, 6, 12, -21, 11, -56, -18, -26, 9, -44, -7, 16, 8, -3, 5, -23, 23, 23, 5, 26, 21, -31, -2, -26, 0, -13, -10, 7, 23, 1, 14, -19, 0, 17, 13, -14, 14, -34, 29, -8, 12, -17, -11, 5, 6, -2, 18, -15, 10, 2, 20, -6, 12, -31, 50, -27, -7, -16, -9, 13, 16, -4, 11, -4, 7, 18, 6, 12, 21, -31, 9, 2, 4, -19, -2, 14, 28, 3, 23, -12, 2, 13, 4, -26, 14, -14, -28, -10, -1, -35, -13, 6, 16, 5, 11, -19, 11, 10, 2, 5, 15, -11, 3, -2, -19, -30, -29, 15, 28, -3, 21, -19, 31, 29, 6, -8, 16, -32, 8, -7, 4, -18, -15, 18, 1, 0, 27, 3, 17, -5, 8, -7, 5, -33, -4, -25, 9, -19, 2, 0, 6, -7, -1, -18, 18, 5, 25, 31, 26, -9, -1, -3, 7, 7, -5, 19, -2, -1, 14, -15, 14, -15, 0, -25, 14, -12, 20, 14, 4, -12, 1, 15, -7, -8, 9, -9, 13, 0, 7, 13, 27, -60, 38, -18, 9, -3, 6, 14, 10, 8, 30, -16, 2, 18, 4, -10, 19, -31, -23, 35, 11, 0, -4, -1, 19, 12, 0, -10, 6, -3, 11, 20, 10, -18, -10, 11, -2, -17, -17, 5, 19, 3, 5, -21, -3, 11, 5, -8, 5, -30, 17, 5, -15, -53, -16, 6, 15, 6, 23, -36, 20, -5, 8, -22, 15, -63, -21, 8, 9, 0, -5, 29, 8, 5, 1, -27, 16, 10, 12, 26, 9, -17, 5, -3, -26, -22, 4, 3, -36, -7, -12, -6, 22, 5, 24, 37, 21, -50, -9, 43, 
  -89, -15, -29, -105, 13, -83, -55, -53, -30, 34, -80, 2, -3, -13, -39, 26, -53, -25, -32, -63, 43, -110, -27, -58, -3, 46, -35, -14, -63, -38, 11, 12, -9, -30, 10, -36, 36, -50, -38, -85, -11, 30, -28, 40, 12, 18, 2, 2, -42, -71, 8, -47, 28, -53, -33, -67, -9, 41, -66, -14, -20, -6, 6, 14, -60, -26, -59, -5, -8, -92, -25, -66, 4, 9, -41, 8, -31, -30, -9, 9, -58, -45, -6, -17, 40, -67, 6, -97, -10, 12, -33, 0, 1, 10, 10, 13, -23, -61, 7, 4, 39, -36, -21, -91, 16, 17, -32, 78, 57, 11, -20, 22, 4, -38, 20, -17, 11, -54, 18, -4, 11, 37, -54, -4, 4, 13, 17, -2, -45, 4, -22, -19, 49, -51, -20, -6, -47, 48, -109, -58, -34, -28, 6, 20, -51, -12, 0, -48, 29, -23, -39, 16, -69, 50, -127, -25, -32, -30, -20, 16, -28, -6, -12, -85, 39, -26, -26, -25, -50, 46, -62, -14, -3, -10, -22, 10, -36, -43, -21, -106, -29, -69, -20, -77, -43, 7, -82, -53, -48, -4, 13, 4, -58, -39, -57, -52, 20, -79, -24, -65, -35, 21, 8, -31, -9, -13, 7, 2, -46, -59, -7, 25, 41, -65, -29, -28, 14, 27, -22, 59, 18, 16, 3, 7, -23, -46, 33, -64, 10, -92, 13, -72, -16, 33, -35, 42, -4, 40, -23, 9, -56, -14, 1, -68, 69, -66, -27, -44, -12, 80, -23, 3, -24, -14, -32, 18, -22, 5, -9, -56, 37, -66, -70, -2, -23, 49, -117, 0, -26, -30, 16, 12, -37, -9, 10, -89, 23, -45, 13, -50, -92, 58, -103, 15, -38, -5, 19, -5, -24, -56, -14, -72, 26, -45, 4, -87, -21, 21, -14, -24, -7, -12, 36, 25, -75, -50, -29, 6, 19, -89, -13, -121, -26, 12, -9, -2, -67, -16, 10, 1, -65, -63, -24, 7, 44, -69, 0, -68, 19, 50, -23, 12, 11, -13, -16, 13, -22, -64, 27, 16, 16, -46, 6, -35, -3, 50, -11, 47, -13, 25, -25, 18, -60, -63, 20, -32, 47, -71, 29, 14, -18, 68, -18, 2, -30, 6, -33, 2, -63, -79, -42, -28, 39, -119, -27, 25, 1, 72, -115, -10, -4, -26, 6, 13, -69, -13, -59, -106, 14, -117, -27, 16, -55, 46, -96, -17, -99, -72, -53, 6, 
  32, 59, 32, -11, -10, 14, 8, 7, -5, 0, -8, -22, -21, 24, 5, 20, 15, 33, 12, 3, -26, 13, -17, 25, -23, -39, -10, -5, -18, 56, 5, 13, 1, 6, 2, 1, -37, -2, -6, 29, 2, -41, -2, 33, -10, 19, -14, 6, 16, 14, 4, -11, -13, -4, -15, 31, -1, -34, 0, -27, -18, 41, -17, 15, 6, 5, 8, -8, -12, 4, -22, 41, -8, -40, 2, 7, 0, 35, 21, 3, 10, -5, 2, -20, -46, -5, -16, 43, -2, -22, 0, 8, -12, 19, 6, 0, -1, 22, 9, -15, -32, 0, -7, 32, 4, -10, -12, -35, -26, 13, -12, -2, 9, 52, 9, -3, -22, 4, -9, 26, 4, -36, 3, 10, -24, 23, 13, 12, 6, 42, 6, -10, -31, 0, 1, 18, -17, -48, 3, -8, -6, 18, 5, -1, 3, 15, 7, 3, -31, 1, 1, 5, 2, -36, 1, 21, -8, 33, -23, 1, 2, 17, 11, 7, -35, 11, -15, 18, 1, -41, -17, 9, -11, 20, -43, 18, 11, 13, 21, -2, -13, 2, -7, 21, -3, -19, -1, 3, -17, 29, -3, 13, 14, 25, 10, -4, -24, 8, -11, 37, 4, -23, 1, 33, -6, 13, 25, 13, 3, 30, 18, -6, -33, 0, -11, 19, -7, -27, -1, -13, -11, 5, -2, 7, 15, 35, 24, -10, -30, 8, -23, 23, -14, -51, 9, 11, -17, 2, -12, 5, 2, 31, 2, -13, -28, 3, -26, 3, -8, -31, -4, 16, 8, 38, 6, 5, -9, 21, 3, 13, -25, 14, 8, 21, -20, -16, -16, -23, -23, 17, -4, -2, -5, -10, 9, -15, -19, 2, -17, 13, -8, -25, 11, 18, -7, 16, -34, 7, -6, 21, 7, -18, -22, 1, -12, 33, -7, -34, -8, -15, -30, 58, -47, 3, -1, 3, 1, -12, -32, 6, -26, 41, 6, -29, -10, 1, -8, 25, 20, -6, 5, 2, 11, 0, -33, -5, 5, 32, -9, -37, -13, -30, -7, 9, 23, -4, 1, 24, 8, -1, -30, -1, -6, 35, 0, -44, -3, 1, 7, 11, -6, -11, 20, 57, 11, -10, -28, 3, -20, 33, -20, -37, -3, 18, -5, 29, 26, 7, 1, 15, 23, -30, -31, 13, 1, 29, -12, -33, -10, -14, -17, 34, -8, 3, 28, 25, 5, 5, -24, 11, 6, -4, -23, -16, -22, -41, -3, 66, 20, -19, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 3,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.018639789894223213, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -1101, -8793, -2061, -4841, -313, -265, -1006, 478, -511, -854, -301, -4590, -537, -1595, -3201, -170, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 0.00030885051819495857, 0.0001627097517484799, 0.00038459076313301921, 9.3456394097302109e-05, 0.00033580910530872643, 0.00037369766505435109, 0.00038628026959486306, 0.00041478170896880329, 0.00058644311502575874, 0.00039348658174276352, 0.0003934130072593689, 0.00021762133110314608, 0.00041055399924516678, 0.00032013843883760273, 0.0001718389248708263, 0.0002238569431938231, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ -105,-24,11,-26,45,-67,2,-6, -127,23,2,-7,9,-93,20,4, -112,-7,-15,-29,84,-54,12,1, 
  /* [1][0][][] */ -96,73,-7,50,-127,-29,-9,8, -88,-10,-19,-13,-74,-74,34,21, -35,20,15,-1,58,-86,13,-7, 
  /* [2][0][][] */ -81,4,8,-18,127,-43,8,4, -104,-6,13,-10,67,-45,2,11, -69,19,-5,-5,74,-10,17,-7, 
  /* [3][0][][] */ -101,-52,68,-41,-18,87,-60,43, 14,-113,-45,122,-127,-119,-36,27, -15,-115,-115,1,-83,-17,21,-7, 
  /* [4][0][][] */ 127,-14,-60,6,-17,-40,4,-43, 2,-19,-43,-4,-18,36,18,-77, -28,35,9,-26,-5,29,-13,-28, 
  /* [5][0][][] */ -127,23,-1,2,-22,-27,2,1, -76,6,-2,-2,22,-10,-2,9, -89,-11,-8,10,-2,-14,-2,1, 
  /* [6][0][][] */ 5,-2,27,-21,-127,-26,-2,16, 21,-21,-24,-15,-83,-1,-5,-5, -6,-58,-44,25,-91,-14,-12,-13, 
  /* [7][0][][] */ -127,-99,-65,-7,-78,-6,15,-60, -108,-76,-55,20,-65,10,9,-94, -121,-124,-70,3,-82,-8,15,-77, 
  /* [8][0][][] */ 9,-16,-5,11,-127,26,5,12, -1,-36,-34,1,-62,-15,-10,0, -9,-34,8,-6,-50,27,-5,-8, 
  /* [9][0][][] */ 127,-13,42,7,6,30,2,13, 29,-45,-18,0,2,2,-11,-17, 52,-85,-35,-1,-3,8,-7,-31, 
  /* [10][0][][] */ 31,-67,-63,9,-119,-2,7,11, 5,-76,-60,6,-127,10,-8,-2, -42,-33,-25,1,-82,55,-5,5, 
  /* [11][0][][] */ -52,-72,2,47,8,24,-21,7, 9,-125,18,-11,127,-15,-11,6, -6,-52,-8,5,17,-66,-27,-3, 
  /* [12][0][][] */ 36,-34,-20,35,-127,-19,4,5, 20,-26,-14,-9,-62,53,-9,0, 4,-4,20,-22,-32,-8,-7,-2, 
  /* [13][0][][] */ -110,13,-2,-30,127,-33,1,-28, -112,-9,-27,-29,11,1,-16,-28, -107,-11,14,0,79,4,-1,-46, 
  /* [14][0][][] */ 3,48,56,-46,-109,8,19,-78, -22,-7,-5,-57,77,-12,36,-71, -5,-38,-64,26,-127,-126,-5,-8, 
  /* [15][0][][] */ 70,-25,9,-127,26,-13,3,1, 10,-39,-2,-106,40,-22,18,-32, 7,-8,35,-113,13,-25,39,-45, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.016390610486268997, 0.0086349612101912498, 0.020410124212503433, 0.0049597048200666904, 0.017821295186877251, 0.019832029938697815, 0.020499786362051964, 0.022012349218130112, 0.031122371554374695, 0.020882222801446915, 0.020878318697214127, 0.011549103073775768, 0.021787986159324646, 0.016989657655358315, 0.0091194435954093933, 0.011880025267601013, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { 538, -21246, -5049, -14879, 950, -81, -11316, -44483, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 9.385548037244007e-05, 2.7156229407410137e-05, 3.5091099562123418e-05, 3.3262404031120241e-05, 9.5789349870756269e-05, 4.1496623452985659e-05, 1.3261698768474162e-05, 2.8016074793413281e-05, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*40] = { 
  /* [0][0][][] */ -49,-11,-108,33,7,7,51,26,6,-32,-97,-52,-15,32,-9,18,37,0,-22,-24,-23,4,6,40,-12,-7,16,-13,-7,46,52,22,-15,-17,43,18,10,27,19,16, -21,23,-114,44,20,1,36,30,-7,-20,-81,-49,-33,63,-26,-11,43,20,-3,12,-37,-12,-7,17,-41,-29,-2,-12,-9,21,37,-2,-51,-43,-9,-4,0,27,11,17, -62,-43,-122,39,15,-15,25,5,-36,-42,-82,-127,-52,-3,-30,-28,-1,7,1,-7,-15,-37,-31,47,5,-24,-23,4,-1,30,20,-36,-77,-49,-28,-28,-14,21,13,11, 
  /* [1][0][][] */ -9,-36,-71,-12,-4,118,15,101,85,127,34,9,38,-15,26,27,-16,45,30,-26,14,-83,2,12,46,35,-7,15,4,45,25,-68,-126,-6,-9,-18,-19,-28,-33,-78, 90,34,-37,5,26,88,37,94,83,87,35,0,37,-15,-57,24,0,18,-22,-65,3,-46,-28,-4,6,44,14,2,-2,59,8,-52,-119,6,-18,-41,-13,-20,-40,-94, -19,-40,-48,-78,-13,118,27,89,69,124,18,47,63,-1,-29,10,-5,65,10,-63,-11,-72,-34,10,46,71,-2,51,-5,19,32,-58,-100,-43,-27,-20,14,-18,-61,-68, 
  /* [2][0][][] */ -1,-63,-96,-55,-9,12,28,55,93,104,46,-24,17,-23,-37,23,11,-6,-4,-25,29,-16,-6,-26,-1,-8,-14,-43,-46,-23,-44,-34,-72,-6,5,-23,18,-24,-18,-37, -8,-71,-75,-15,-5,5,-2,40,127,96,77,-7,-5,32,10,26,-16,-10,-5,-12,3,8,-4,-29,-21,23,-12,-18,-57,-18,-34,-28,-79,-12,-17,-22,-10,13,-33,-50, 24,-86,-112,-63,1,-10,1,45,93,114,55,22,39,42,6,31,-3,-6,19,-32,27,4,10,-1,20,-7,19,-11,-29,21,12,-20,-36,-4,27,1,40,49,5,-16, 
  /* [3][0][][] */ -53,77,-10,64,10,-29,32,14,-45,-19,12,-14,41,54,32,-61,-16,-27,-20,13,17,16,18,34,8,31,68,9,31,-16,13,87,127,65,36,31,-18,-5,-4,56, -16,52,11,32,-16,-71,-2,-31,-48,-39,-6,-26,32,46,50,-76,-11,-45,-49,9,-9,12,-4,49,-9,-21,56,-9,1,-38,9,86,107,37,9,5,-29,-35,19,7, -21,77,25,25,-25,-66,-56,-49,-102,-65,-13,-25,26,54,24,-52,-31,-45,-62,6,-62,-7,-40,23,-32,-23,47,-12,-1,-48,-4,26,88,29,-12,-2,-31,-53,-37,-8, 
  /* [4][0][][] */ -58,-92,79,-1,-23,15,2,7,12,7,14,33,7,-16,-1,11,-6,-8,1,-17,-22,-66,2,-26,13,1,-18,15,-19,-34,-2,44,-24,-35,-33,-13,10,11,6,13, -55,-94,78,-12,-23,19,11,-9,45,-1,23,19,-3,2,-3,4,-1,18,13,-8,-5,-41,35,-13,21,6,-5,1,-17,-33,-10,47,-22,-42,-12,-1,2,2,-3,10, -83,-127,57,6,-28,27,2,33,31,8,18,9,-1,-7,-13,9,4,8,8,-12,-10,-63,33,-30,29,0,-9,7,-26,-36,-6,38,-6,-29,-23,-7,12,-1,4,5, 
  /* [5][0][][] */ -100,104,-88,12,22,-48,-16,-15,-33,37,60,28,28,-15,11,6,23,35,-43,57,6,65,15,-43,35,-1,-18,-15,55,72,-77,-49,36,15,-10,-27,-115,-101,-78,-45, -110,59,-127,9,-26,-94,4,-29,-101,-44,-6,-55,-59,-61,-45,-42,-19,-50,-74,0,-49,8,-19,-22,-4,1,-28,15,95,53,-47,-43,10,23,-24,-7,-51,-61,-82,-86, -59,8,-10,-6,93,69,73,83,66,74,49,49,14,-14,4,37,40,-38,-26,-7,-39,37,-46,-7,5,27,47,0,97,45,21,15,50,47,21,1,14,-5,-17,7, 
  /* [6][0][][] */ -19,21,-38,-31,-55,-58,-89,-99,-112,-89,-67,-32,-77,-53,-35,-50,-59,7,-36,-45,-53,-5,-29,-4,-45,-26,15,-32,-37,-55,-27,-74,16,-47,-47,34,-37,97,-34,-47, -73,-102,-19,-50,-78,12,-27,-44,-56,-40,-78,4,-108,-9,-3,-54,-69,-91,-14,-7,-65,-92,-53,-39,-87,10,-49,-25,-76,-70,15,12,-88,-13,-85,8,28,13,-97,-89, -58,-90,-90,-57,-104,-88,-79,-98,-30,-7,-127,-101,-66,-92,-97,-75,-2,-91,-52,-81,-42,-98,-6,-44,-39,-53,-99,-68,-77,-18,-76,-61,-63,-12,-46,14,-55,-84,-107,-43, 
  /* [7][0][][] */ 53,70,-8,79,59,32,-17,127,60,20,46,-42,16,51,22,-76,-47,-12,-73,-55,-1,-13,-30,-17,30,31,60,43,4,-36,-41,30,108,119,38,11,11,-14,14,22, 67,89,-83,36,0,-10,10,124,49,7,50,-30,26,81,15,-87,-64,-48,-75,-71,0,-27,-11,0,-7,14,38,19,-24,-71,-63,29,98,96,58,17,-2,-5,-14,16, 26,97,-78,33,-33,-33,-78,83,18,-9,-25,-4,9,82,22,-65,-37,-23,-64,-57,-12,-29,-21,-5,-52,21,47,18,-47,-49,-26,53,47,81,18,21,-34,-44,-7,8, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,40 } };
const TfArray<8, float> quant11_scale = { 8, { 0.025961380451917648, 0.0075116893276572227, 0.0097065549343824387, 0.0092007191851735115, 0.026496307924389839, 0.011478387750685215, 0.0036683208309113979, 0.007749530952423811, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,98,40 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,98,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.018843136727809906, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,98,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,49,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,49,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,49,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.059137545526027679, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,49,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,3 } };
const TfArray<1, float> quant21_scale = { 1, { 0.93805205821990967, } };
const TfArray<1, int> quant21_zero = { 1, { 4 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3920), (TfLiteIntArray*)&g0::tensor_dimension0, 3920, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 3920, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3920), (TfLiteIntArray*)&g0::tensor_dimension13, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 784), (TfLiteIntArray*)&g0::tensor_dimension15, 392, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 392, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 784), (TfLiteIntArray*)&g0::tensor_dimension17, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 784), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_919603_7_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_919603_7_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_919603_7_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_919603_7_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_919603_7_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
